version: "3"
services:
    adventureworks2022:
        build: ./src
        environment:
            SA_PASSWORD: "P@ssword01"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            MSSQL_COLLATION: "Latin1_General_CI_AS"
            MSSQL_PID: "Developer"
        ports:
            - "1433:1433/tcp"
        container_name: adventureworks2022
        hostname: adventureworks2022
        stdin_open: true
        tty: true